#!/usr/bin/env bash
# Prints 1 - 20; "bad luck from China" as the fourth,
# "bad luck from Japan" the nineth, and "bad luck from Italy" the seventeenth

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done
